[param]
interface_type = "uart"
comport_uart = "COM7"
speed_uart = "2000000"
speed_jlink = "1000"
chip_xtal = "40M"
ota = ""
version = ""
aes_key = ""
aes_iv = ""
addr = "0x0"

[check_box]
fw_download = true
mfg_download = false
media_download = false
romfs_download = false
psm_download = false
key_download = false
data_download = false
factory_download = true
boot2_download = true
ckb_erase_all = "False"
partition_download = true
encrypt = false
sign = false
single_download = false

[input_path]
fw_bin_input = "//192.168.1.102/ubuntu20/Ai-WB2/Ai-Thinker-WB2/applications/peripherals/demo_dac/build_out/main.bin"
mfg_bin_input = ""
media_bin_input = ""
romfs_dir_input = ""
psm_bin_input = ""
key_bin_input = ""
data_bin_input = ""
factory_bin_input = "D:/Desktop/v1.8.1/v1.8.1/chips/bl602/device_tree/bl_factory_params_IoTKitA_40M.dts"
boot2_bin_input = "D:/Desktop/v1.8.1/v1.8.1/chips/bl602/builtin_imgs/boot2_isp_bl602_v6.5.1/boot2_isp_release.bin"
img_bin_input = ""
pt_table_bin_input = "D:/Desktop/v1.8.1/v1.8.1/chips/bl602/partition/partition_cfg_4M.toml"
publickey = ""
privatekey = ""
