[param]
interface_type = "uart"
comport_uart = "COM4"
speed_uart = "921600"
speed_jlink = "1000"
chip_xtal = "40M"
aes_key = ""
aes_iv = ""
ota = ""
version = ""
addr = "0x0"

[check_box]
factory = true
partition_download = true
boot2_download = true
bin_download = true
media_download = false
romfs_download = false
mfg_download = false
ro_params_download = true
ckb_erase_all = "True"
encrypt = false
sign = false
single_download = false

[input_path]
dts_input = "D:\\Ai-Thinker-WB2\\tools\\flash_tool\\chips\\bl602\\device_tree\\04-bl_factory_params_IoTKitA_40M-20220625.dts"
pt_bin_input = "D:\\Ai-Thinker-WB2\\tools\\flash_tool\\chips\\bl602\\partition\\partition_cfg_2M.toml"
boot2_bin_input = "D:\\Ai-Thinker-WB2\\tools\\flash_tool\\chips\\bl602\\builtin_imgs\\boot2_isp_bl602_v6.5.1\\boot2_iap_release.bin"
cfg2_bin_input = "D:\\Ai-Thinker-WB2\\applications\\get-started\\blink\\build_out\\blink.bin"
media_bin_input = ""
romfs_dir_input = ""
mfg_bin_input = ""
publickey = ""
privatekey = ""
img_bin_input = ""
